# Generated by Django 4.2.21 on 2025-05-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
